# JUPYTER NOTEBOOK FOR HOMEWORK 2 - question 1
Extracting texture features and matching them for scene classification

In [2]:
import os, glob, time, sys
import pandas as pd
from tqdm import tqdm

from skimage import io, transform
from skimage.filters.edges import convolve
from skimage import color
from skimage.transform import resize
import numpy as np

import joblib
import matplotlib.image as mpimg
from sklearn.cluster import MiniBatchKMeans, KMeans
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler #use for data normalization

from makeLMfilters import makeLMfilters
np.random.seed(42)

E:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
E:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


## 1. Load the training and testing images from the two .CSV files respectively

In [3]:
ori_file = pd.read_csv('train_caleb_idea.csv',header=None)
ori_file = np.asarray(ori_file)
# print(ori_file)

new_ori = []

for line in ori_file[1:]:
    tmp = ['ISIC_2019_Training_Input/ISIC_2019_Training_Input/' + str(line[0]) + '.jpg']
#     print(tmp)
    if line[1] == '1':
        tmp.append('MEL')
    elif line[2] == '1':
        tmp.append('NV')
    elif line[3] == '1':
        tmp.append('BCC')
    elif line[4] == '1':
        tmp.append('AK')
    elif line[5] == '1':
        tmp.append('BKL')
    new_ori.append(tmp)
new_ori = pd.DataFrame(new_ori)
# print(new_ori)



new_ori.to_csv('isic_new.csv',index=False,sep=',')
print('e')



e


In [4]:
ori_file = pd.read_csv('test_caleb.csv',header=None)
ori_file = np.asarray(ori_file)
new_ori = []

for line in ori_file[1:]:
    tmp = ['ISIC_2019_Training_Input/ISIC_2019_Training_Input/' + str(line[0]) + '.jpg']
#     print(tmp)
    if line[1] == '1':
        tmp.append('MEL')
    elif line[2] == '1':
        tmp.append('NV')
    elif line[3] == '1':
        tmp.append('BCC')
    elif line[4] == '1':
        tmp.append('AK')
    elif line[5] == '1':
        tmp.append('BKL')
    new_ori.append(tmp)
new_ori = pd.DataFrame(new_ori)
# print(new_ori)



new_ori.to_csv('isic_new_test.csv',index=False,sep=',')
print('test')

test


In [5]:
#Load the data along with the class labels
# Note, you will need to use the file folder name to determine the label of an image
# Convert the images to grayscale and resize them to 128 x 128
# (Optional) You might want to save your data here (to avoid repeating this step)
'*** Enter your code below'




train_path = pd.read_csv('isic_new.csv', header=None)
train_path = np.array(train_path[1:])
# print(train_path)
train_all_set = []
train_label = train_path[:,1]
print(train_label)
for path in train_path:
    temp_img_path = path[0]
    
#     print(temp_img_path)
    img_rgb = io.imread(temp_img_path)
    temp_gry = color.rgb2gray(img_rgb)
    temp_gry = resize(temp_gry,(128,128))
    train_all_set.append(temp_gry)
#     print(len(train_all_set))
train_all_set = np.array(train_all_set)
print(train_all_set.shape)
print(train_label.shape)

test_path = pd.read_csv('isic_new_test.csv', header=None)
test_path = np.array(test_path[1:])
test_all_set = []
test_label = test_path[:,1]
for path in test_path:
    temp_img_path = path[0]
    img_rgb = io.imread(temp_img_path)
    temp_gry = color.rgb2gray(img_rgb)
    temp_gry = resize(temp_gry,(128,128))
    test_all_set.append(temp_gry)

test_all_set = np.array(test_all_set)
print(test_all_set.shape)
print(test_label)

['MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL'
 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL'
 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL' 'MEL'
 'MEL' 'MEL' 'MEL' 'MEL' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV'
 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV'
 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV' 'NV'
 'NV' 'NV' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC'
 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC'
 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC'
 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'BCC' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK'
 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK'
 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK' 'AK'
 'AK' 'AK' 'AK' 'AK' 'AK' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL'
 'BKL' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL' 'BKL

## 2. Apply a bank of filters and generate features for training, testing and save the dataset

In [37]:
#. Using the overcomplete bank of filters F provided, convolve your input image with each filter in the bank
#  (make sure you check the dimensions of the returned array)
#
def getAbsFilterResponses( F, imggray ):
    rows, cols = imggray.shape
    num_filters = F.shape[2]
    responses = np.zeros((rows, cols, num_filters))

    #. Convolve the input image with every filter in the bank of filters 
    #   to get a response array; take the absolute value of the values in the array
    '*** Enter your code below'
    for i in range(num_filters):
        responses[:,:,i] = np.abs(convolve(imggray,F[:,:,i]))
        
    print('response:',responses.shape)
    return responses


In [38]:

def apply_filter_bank( df, desc ):
    F = makeLMfilters() # This creates the over-complete bank of filters F
    X = np.array([])    # Initialize the numpy array to stack the responses for each image
    y = []              # The label for each image

    X_tmp = []
    for i in df:
        response = getAbsFilterResponses(F,i)
        X_tmp.append(response)
        
    X = np.array(X_tmp)
    if desc == "Training->":
        y = train_label
    elif desc == "Testing->":
        y = test_label
    else:
        print("Wrong Parameter.")
    print('X:',X.shape)
    return X, y

In [39]:
## generate training and testing features, save them in a pickle with joblib
# NOTE: The code in this cell has been written for you
# NOTE2: This process can take a VERY LONG TIME...
#
X_train, y_train = apply_filter_bank( train_all_set, 'Training->' )
X_test, y_test = apply_filter_bank( test_all_set, 'Testing->' )
print(X_train.shape)

# save the dataset, pickle using joblib
dataset = f'data.pkl'
obj = {
    'train': {
        'features': X_train,
        'label': y_train
    },
    'test': {
        'features': X_test,
        'label': y_test
    }
}

testc = 0

with open( dataset, 'wb' ) as f:
    print(testc)
    testc += 1
    joblib.dump( obj, f, compress=3 )

response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)


response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)
response: (128, 128, 48)


Load back the dataset (optional)
## 3. Run Kmeans with k=500 (recommended)
save the model again (optional)

In [6]:
# load back the dataset (optional)
# NOTE: The code in this cell has been written for you
dataset = f'data.pkl'
with open( dataset, 'rb' ) as f:
    obj = joblib.load( f )
print ( 'finished loading pkl file back')
    
X_train, y_train = obj['train']['features'], obj['train']['label']
X_test, y_test = obj['test']['features'], obj['test']['label']
print( f'X_train shape: {X_train.shape}; y_train shape: {len(y_train)}; X_test shape: {X_test.shape}; y_test shape: {len(y_test)}' )

finished loading pkl file back
X_train shape: (200, 128, 128, 48); y_train shape: 200; X_test shape: (200, 128, 128, 48); y_test shape: 200


In [21]:
# Vectorize the training set 
# NOTE: The vectorization code has been written for you below
reshape_X_train = X_train.reshape( -1, 48 )
print( f'Training dataset shape: {reshape_X_train.shape}' )

# normalize the the reshaped data (recommended to use MinMaxScaler)
'*** Enter your code below' 
scaler = MinMaxScaler()
scaler.fit(reshape_X_train)
data = scaler.transform(reshape_X_train)

print(data)


# run kmeans (because the data is large, recommended to run minibatch kmeans)
# NOTE: This process can take a VERY LONG TIME...
'*** Enter your code below' 
model_3 = MiniBatchKMeans(n_clusters=250)
model_3.fit(data)
kmeans = model_3


# save kmeans model (optional)
# NOTE: The data saving code has been written for you below
model = f'kmeans_model.pkl'
with open( model, 'wb' ) as f:
    joblib.dump( kmeans, f, compress=3 )
print( f'Kmeans model saved.' )

Training dataset shape: (3276800, 48)
[[0.0422687  0.01458762 0.01100722 ... 0.3372853  0.56326979 0.71657651]
 [0.04210604 0.01793488 0.02504564 ... 0.33900262 0.56131043 0.71047971]
 [0.04174733 0.02074654 0.02894426 ... 0.34236832 0.55732834 0.69780342]
 ...
 [0.0024177  0.01449062 0.04607636 ... 0.64979427 0.5951626  0.17694544]
 [0.00246224 0.01023069 0.02834617 ... 0.65000031 0.59633479 0.1798255 ]
 [0.00248376 0.0027548  0.00943074 ... 0.65012492 0.5970492  0.18153535]]
Kmeans model saved.


## 4. Generate the frequency histogram (feature) for each image

In [22]:
# load the model (optional)
model = f'kmeans_model.pkl'
with open( model, 'rb' ) as f:
    kmeans = joblib.load( f )

In [23]:
# Given an image response (already filtered) and the kmeans model, compute its frequency histogram
# a) Vectorize the response image
# b) Max-min normalize the response
# c) Predict clusters for each 48-dimensional pixel using the k-means predict function
# d) Generate the frequency histogram by incrementing the cluster centers where each pixel belongs
# e) Normalize the resulting frequency histogram so that it sums to 1
def clac_freq( img, kmeans ):
    scaler_ = MinMaxScaler()
    ver_img = img.reshape(-1,48)
    scaler_.fit(ver_img)
    ver_img = scaler_.transform(ver_img)
    
    pix_pre = kmeans.predict(ver_img)
#     pix_pre = np.array(pix_pre)
#     print(pix_pre.shape)
    model_center = kmeans.cluster_centers_
#     print(model_center.shape)
    
    hist = [0]*model_center.shape[0]
    for i in pix_pre:
        hist[i] += 1
    
    
    sum_norm = sum(hist)
    
    img_hist = np.array(hist)
    img_hist = img_hist/sum_norm
    
    return img_hist #this is the histogram feature representing an image

In [24]:
# loop through the set and call calc_freq on each image in the set (training and testing)
'*** Enter your code below'
train_res = []
test_res = []
for i in range(200):
    train_temp = clac_freq(X_train[i,:,:,:],kmeans)
    test_tmp = clac_freq(X_test[i,:,:,:],kmeans)
    train_res.append(train_temp)
    test_res.append(test_tmp)
    
train_res = np.array(train_res)
test_res = np.array(test_res)
print(train_res.shape)
print(test_res)

(200, 250)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## 5. Implement the "nearest neighbor classifier" by comparing each image in Testing with the reference training images to generate a label.
Compare using chi-square distance measure

In [25]:
# Implement a function to calculate chi-square distance between 2 histograms ref and img
#
def calc_chi_sq( ref, img ):
    '*** Enter your code below'
    dist = (1/2) * np.sum(np.square((ref-img))/((ref+img)+((ref+img)==0)))
    return dist

In [26]:
# Using the chi-sq distances between each img in training
# and each image in test, find the closest match for each test img in training, 
#  assign the label of the closest match to that test img
# Your output will be 'y_pred', the array of predicted test labels.
'*** Enter your code below'
chi_pred = []
y_pred = []

for i in range(len(test_res)):
    distance = []
    for j in range(len(train_res)):
        dis_tmp = calc_chi_sq(test_res[i],train_res[j])
        distance.append(dis_tmp)
        
    
    dist_index = distance.index(min(distance))
    chi_pred.append(dist_index)
print(len(chi_pred))

for i in range(len(chi_pred)):
    y_pred.append(train_label[chi_pred[i]])
print(len(y_pred))
# print(train_label == y_train)


# distance = np.asarray(distance)
# print(distance.shape)

print('predict labels over.')



200
200
predict labels over.


## 6. Generate a class confusion matrix and print out your accuracy specifically

In [27]:
# Using y_test (true labels on the test data) and y_pred (the predicted labels), 
#  call the appropriate library function to display your confusion matrix, 
#  ensuring that the labels corectly match up with the folder names given
'*** Enter your code below'
from sklearn.metrics import confusion_matrix
import seaborn as sn
cm = confusion_matrix(test_label, y_pred)
ling = ['MEL', 'NV', 'BCC', 'AK', 'BKL']
sn.heatmap(cm, annot=True, xticklabels=ling, yticklabels=ling)
# print(confusion_matrix(test_label, y_pred))
tt = test_label == y_pred
# print(tt)
print('accuracy :', np.sum(tt!=0)/len(tt))


accuracy : 0.56
